language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
services:
  - postgresql
# command to install dependencies
install:
  - pip install -e .
  - pip install codecov pytest-cov
before_script:
  - psql -c "create user sixquiprend with password 'sixquiprend';" -U postgres
  - psql -c "alter user sixquiprend createdb;" -U postgres
# command to run tests
script: py.test --cov=./
after_success:
  - codecov
